---
name: Verify BuildConfigs
on:
  workflow_dispatch:

jobs:
  Verify-buidConfigs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Update BuildConfig for CUDA RStudio
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          while IFS= read -r line; do
            if [[ "$line" == *"ref: rhoai-"* ]]; then
              numstr=${line#*2.}
              num=$(expr "$numstr" + 1)
              echo "      ref: rhoai-2.$num" >> tmp.yaml
            else
              echo "$line" >> tmp.yaml
            fi
          done < ./manifests/base/cuda-rstudio-buildconfig.yaml
          cat tmp.yaml > ./manifests/base/cuda-rstudio-buildconfig.yaml
          rm tmp.yaml
        
      - name: Update BuildConfig for RStudio
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          while IFS= read -r line; do
            if [[ "$line" == *"ref: rhoai-"* ]]; then
              numstr=${line#*2.}
              num=$(expr "$numstr" + 1)
              echo "      ref: rhoai-2.$num" >> tmp.yaml
            else
              echo "$line" >> tmp.yaml
            fi
          done < ./manifests/base/rstudio-buildconfig.yaml
          cat tmp.yaml > ./manifests/base/rstudio-buildconfig.yaml
          rm tmp.yaml
      
      - name: Create Target Branch
        run: |
          git checkout -b $tmp_BRANCH
          git push origin $tmp_BRANCH
      
      - name: create pull request
        run: |
          git add ./manifests/base/cuda-rstudio-buildconfig.yaml
          git add ./manifests/base/rstudio-buildconfig.yaml
          git commit -m "Update BuildConfigs for CUDA RStudio and RStudio"
          git push origin $tmp_BRANCH
          gh pr create -B $test -H $tmp_BRANCH --title "$PR_TITLE" --body "$PR_BODY"
        env:
          