---
name: Verify BuildConfigs
on:
  workflow_call

jobs:
  Verify-buidConfigs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create Target Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git checkout -b tmp_BRANCH
          git push origin tmp_BRANCH
        
      
      - name: Update BuildConfig for CUDA RStudio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          while IFS= read -r line; do
            if [[ "$line" == *"ref: rhoai-"* ]]; then
              numstr=${line#*2.}
              num=$(expr "$numstr" + 1)
              echo "      ref: rhoai-2.$num" >> tmp.yaml
            else
              echo "$line" >> tmp.yaml
            fi
          done < ./manifests/base/cuda-rstudio-buildconfig.yaml
          cat tmp.yaml > ./manifests/base/cuda-rstudio-buildconfig.yaml
          rm tmp.yaml
        
      - name: Update BuildConfig for RStudio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          while IFS= read -r line; do
            if [[ "$line" == *"ref: rhoai-"* ]]; then
              numstr=${line#*2.}
              num=$(expr "$numstr" + 1)
              echo "      ref: rhoai-2.$num" >> tmp.yaml
            else
              echo "$line" >> tmp.yaml
            fi
          done < ./manifests/base/rstudio-buildconfig.yaml
          cat tmp.yaml > ./manifests/base/rstudio-buildconfig.yaml
          rm tmp.yaml
      
      - name: create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          git add ./manifests/base/cuda-rstudio-buildconfig.yaml
          git add ./manifests/base/rstudio-buildconfig.yaml
          git commit -m "Update BuildConfigs for CUDA RStudio and RStudio"
          git push origin tmp_BRANCH
          gh pr create -B test -H tmp_BRANCH --title "Update BuildConfigs for CUDA RStudio and RStudio" --body "This is an automated Pull Request to update the BuildConfigs for CUDA RStudio and RStudio."

      - name: Clean up
        run: |
          git checkout main
          git branch -D tmp_BRANCH
          git push origin --delete tmp_BRANCH || true
          echo "Temporary branch deleted."
          